version: '3.3'

services:
  cdn:
    build: .
    container_name: dttrilhas_cdn
    volumes:
      - /root/tema:/root/tema
      # - /home/lucas/tema:/home/lucas/tema
    ports:
      - "3001:3001"
  web:
    image: nginx
    container_name: nginx_cdn
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - "80:80"
    depends_on:
      - cdn